#!/bin/bash

error=0
red='\033[0;31m'
yellow='\033[0;33m'
nc='\033[0m'


toolbox_name=toolbox
script_dir=$(dirname $0)
cd ${script_dir}
## check that dependencies are installed
command -v docker >/dev/null 2>&1 || { echo -e >&2 "${red}ERROR: ${yellow}docker${nc} is required, but not installed";error=1; }
command -v docker-compose >/dev/null 2>&1 || { echo -e >&2 "${red}ERROR: ${yellow}docker-compose${nc} is required but not installed";error=1; }

if [ "$1" == 'restart' ]; then
    docker-compose down
fi

if [[ "${error}" == 1 ]]; then
    echo "Please install dependencies before continuing"
    exit 1
fi


if [ "$(docker-compose top)" == "" ]; then
    docker-compose up -d
fi
exec docker-compose exec toolbox zsh
