cache deny all
cache_mem 16 MB

pid_filename /var/run/squid.pid

http_port 127.0.0.1:3128

acl Safe_ports port 443
acl Safe_ports port 80
acl CONNECT method CONNECT

## To limit, uncomment and set up whitelist and comment out http_access allow all
# acl allowed_dst ssl::server_name "/etc/squid/whitelist_domains.txt"
# http_access allow CONNECT allowed_dst
# http_access deny all
http_access allow all

access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log

dns_nameservers 9.9.9.9 149.112.112.112
